rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: root
    RABBITMQ_DEFAULT_PASS: root
    RABBITMQ_DEFAULT_VHOST: vhost

database:
  image: mysql:5.7
  container_name: database.dev
  command: mysqld --user=root --verbose
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "root"